/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccesLogs: typeof import('./src/components/AccesLogs.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CodeForm: typeof import('./src/components/CodeForm.vue')['default']
    EmailForm: typeof import('./src/components/EmailForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentList: typeof import('./src/components/StudentList.vue')['default']
  }
}
