FROM alpine:latest
ARG BUILD_DATE=2025-01-25_v5
RUN apk add --no-cache build-base git cmake linux-headers curl-dev curl
WORKDIR /app
RUN git clone --depth 1 https://github.com/ggerganov/llama.cpp.git .
RUN cmake -B build -DGGML_BACKTRACE=OFF -DGGML_NATIVE=ON
RUN cmake --build build --config Release --target llama-server -j4
RUN cp build/bin/llama-server .
EXPOSE 8080
ENTRYPOINT ["./llama-server"]