FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY . .

RUN mkdir -p uploads && chown -R node:node /app

USER node

EXPOSE 3001

CMD ["node", "server.js"]